version: '3.8'

services:
  ecotextile:
    build: ./
    env_file:
      - .env
    networks:
      - proxy
      - nginx_network
    command: /bin/sh -c "./script.sh"
    volumes:
      - ./:/ecotextile/
      - ./static/:/ecotextile/static/
      - ./media/:/ecotextile/media/
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.6-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5437:5432"
    expose:
      - 5432
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data_atl/

  celery:
    build: .
    env_file:
      - .env
    command: celery -A ecotextile worker -B -l info
    restart: always
    networks:
      - proxy
    depends_on:
      - ecotextile
      - redis

  redis:
    hostname: redis
    image: redis:alpine
    networks:
      - proxy
    ports:
      - "6379:6379"
    expose:
      - 6379

  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./static/:/ecotextile/static/
      - ./media/:/ecotextile/media/
    networks:
      - nginx_network
    depends_on:
      - ecotextile

networks:
  proxy:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data: