version: '3.3'

services:
  ecotextile:
    build: ./
    env_file:
      - .env
    networks:
      - proxy
      - nginx_network
    command: /bin/sh -c "./script.sh"
    volumes:
      - ./:/ecotextile/
      - ./static/:/ecotextile/static/
      - ./media/:/ecotextile/media/
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.6-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5437:5432"
    expose:
      - 5432
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data_atl/
networks:
  proxy:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data: