# Generated by Django 4.1.6 on 2023-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
